name: Conditional Workflow

on:
  push:
    branches: [main]

jobs:
  show-context:
    runs-on: ubuntu-latest

    steps:
      - name: Show GitHub variable
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"

  water-job:
    runs-on: ubuntu-latest
    needs: show-context

    steps:
      - name: Define variable
        run: echo "water=cold" >> $GITHUB_ENV

      - name: Display variable
        run: |
          echo "Water is $water"

      - name: Conditional step
        if: ${{ env.water == 'cold' }}
        run: echo "Water is cold, job executed"
